apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      chart: wordpress
      version: 24.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
  targetNamespace: wordpress
  releaseName: wordpress
  interval: 50m
  install:
    remediation:
      retries: 3
