apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/rancher/local-path-provisioner
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
  path: ./deploy/
  prune: true
  wait: true
  timeout: 5m0s
